### ISSUE TITLE
how does diskscan compare with badblocks?

### ISSUE THREAD

**Issue by anarcat** [baruch/diskscan#35]
badblocks has been there for a while, and is well supported on every linux system. how does diskscan compare with it, and why is it necessary?

thanks!

**Comment by baruch** [comment]
badblocks is intended for a simple task, to find bad blocks in the media. diskscan is trying to say a lot more about the media, specifically it is trying not just to say where is a bad block but also what blocks are already deteriorated but still readable and also give information on the latency of reading each block which should help to give an overall assessment of the disk media.

In essence badblocks looks for fatal issues already happening and diskscan is for upcoming issues that can be fixed.

Also, badblocks is essentially obsolete in this day and age since the disks themselves will reallocate the data and there is no real need to map the bad blocks in the filesystem level anymore.

**Comment by anarcat** [comment]
good job with the docs, thanks for the feedback!

i added this tool to our inventory here https://wiki.koumbit.net/DiskMaintenance#diskscan
